= 2018 北京 qcon 大会笔记

4月22日下午去听了半天的 Qcon 软件开发大会分享. 主要是服务化探索的内容.

== 第一场:阿里巴巴微服务技术实践

这一场虽然名字是"阿里巴巴微服务实践", 但主要讲的是一个名为 "Pandora" 的服务隔离框架, 和为了这个框架能够方便使用的 "Pandora boot"

先说一下历史背景:

服务化在阿里的过程:

=== all in one
最早很自然都是 all in one, 一个大的系统所有功能都在一个项目里.

=== 代码共享
然后在09-12年, 做项目拆分, 但是是通过代码共享, 即业务功能写完后, 发布成 jar 包, 供几个项目引用.

这里我不得不吐槽, 我在15年也是这么做的, 现在接手的新项目也是这么做的. 显然是很不爽的, 因为修改一个业务逻辑, 就要生成新的 jar 包发布出去, 然后凡是依赖这个 jar 包的应用都要进行更新.

反过来说, 当你在关注一个应用时, 需要修改它的逻辑, 发现逻辑放在底层的 jar 包里, 需要另开一个项目更改, 很烦.

我最初这么做的想法, 无非是想避免同样的逻辑在不同的系统里写多次, 尤其是数据存取的那些逻辑, 毕竟在 java 里写 pojo mapper 很繁琐, 不能没个项目里都维护一份. 

现在看来, 这种写法非常教条化.

=== api
12年到15, 16年. 就向每个系统代码相互独立, 系统间通过 api 进行交互.

这也就是我们现在通常所认为的微服务.

== 问题
在以上服务化演进过程中, 就产生了一些中间件来支持每个应用. 比如 HSF中间件, 消息中间件, tddl, tair, ons 等阿里内部的中间件系统.

这样业务系统就会因为这些中间件的 client 端或者 sdk.

产生了一下问题:

* 中间件统一运维, 统一更新, 要求业务方应用更新 client 和 sdk.
* 中间件 client 或 sdk 的依赖与业务方应用所需要的依赖冲突.
+
比如某个中间件 client 用到 netty 是 4.0.* , 而业务方应用的功能需要依赖 netty 4.1.*
* 不同中间件之间的所需依赖冲突

== "Pandora" 出现
"Pandora" 就是这种背景产生下的隔离容器.

是基于 java 的 classloader 体系, 通过在 tomcat 等容器上配置自定义的 pandora classloader, 实现加载不同的中间件及其依赖的 class 时, 到不同的目录来查找.

在业务应用部署时, 一个包含了所有中间件依赖的 "Pandora" 目录会部署在项目目录下.

== "Pandora" 问题

这一套东西用起来很麻烦, 本地开发需要引这样一堆组件



